product = input()
weight = int(input())
price = int(input())
quanity = int(input())
print('Чек')
print(f'{product} - {weight}кг - {price}руб/кг')
print(f'Итого: {weight * price}руб')
print(f'Внесено: {quanity}руб')
print(f'Сдача: {quanity - weight * price}руб')